PRICE_LIST_PRE_RELEASE = "PR"
PRICE_LIST_RELEASE = "RE"
PRICE_LIST_STATUS_TYPES = (
    (PRICE_LIST_PRE_RELEASE, "Pre-Release"),
    (PRICE_LIST_RELEASE, "Release")
)

CHARGE_LIST_OPEN = "OP"
CHARGE_LIST_CLOSED_PENDING_PAYMENT = "CP"
CHARGE_LIST_CLOSED_PAYMENT_RESOLVED = "CR"
CHARGE_LIST_STATUS_CHOICES = (
    (CHARGE_LIST_OPEN, "Open"),
    (CHARGE_LIST_CLOSED_PENDING_PAYMENT, "Closed (Pending Payment)"),
    (CHARGE_LIST_CLOSED_PAYMENT_RESOLVED, "Closed")
)

RENTAL_DELIVERY_REQUESTED = "DR"
RENTAL_DELIVERED_TO_STATION = "DS"
RENTAL_STATUS_TYPES = (
    (RENTAL_DELIVERY_REQUESTED, "Delivery Requested"),
    (RENTAL_DELIVERED_TO_STATION, "Delivered to Station"),
)

TIME_MEASUREMENT_HOUR = 60
TIME_MEASUREMENT_DAY = 1440
TIME_MEASUREMENT_CHOICES = (
    (TIME_MEASUREMENT_HOUR, "Hour"),
    (TIME_MEASUREMENT_DAY, "Day")
)

STATION_RIG = 'RG'
STATION_OFFICE = 'OF'
STATION_OTHER = 'OT'
STATION_TYPE_CHOICES = (
    (STATION_RIG, "Rig"),
    (STATION_OFFICE, "Office"),
    (STATION_OTHER, "Other")
)