PRICE_LIST_PRE_RELEASE = "PR"
PRICE_LIST_RELEASE = "RE"
PRICE_LIST_STATUS_TYPES = (
    (PRICE_LIST_PRE_RELEASE, "Pre-Release"),
    (PRICE_LIST_RELEASE, "Release")
)

CHARGE_LIST_OPEN = "OP"
CHARGE_LIST_CLOSED = "CL"
CHARGE_LIST_STATUS_TYPES = (
    (CHARGE_LIST_OPEN, "Open"),
    (CHARGE_LIST_CLOSED, "Closed")
)

RENTAL_AWAITING_DELIVERY = "AD"
RENTAL_DELIVERED_TO_RIG = "DR"
RENTAL_REMOVED_FROM_RIG = "RR"
RENTAL_STATUS_TYPES = (
    (RENTAL_AWAITING_DELIVERY, "Awaiting Delivery"),
    (RENTAL_DELIVERED_TO_RIG, "Delivered to Rig"),
    (RENTAL_REMOVED_FROM_RIG, "Removed from Rig")
)

TIME_MEASUREMENT_HOUR = 60
TIME_MEASUREMENT_DAY = 1440
TIME_MEASUREMENT_CHOICES = (
    (TIME_MEASUREMENT_HOUR, "Hour"),
    (TIME_MEASUREMENT_DAY, "Day")
)

STATION_RIG = 'RG'
STATION_OFFICE = 'OF'
STATION_OTHER = 'OT'
STATION_TYPE_CHOICES = (
    (STATION_RIG, "Rig"),
    (STATION_OFFICE, "Office"),
    (STATION_OTHER, "Other")
)